"""add_solar_simulations

Revision ID: 152c2219e0b0
Revises: 4fb4c643ead5
Create Date: 2026-05-19 15:10:33.405609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '152c2219e0b0'
down_revision: Union[str, None] = '4fb4c643ead5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solar_simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('shade_ratio_annual', sa.Float(), nullable=False),
    sa.Column('shade_ratio_by_month', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('peak_shade_hour_utc', sa.String(length=5), nullable=True),
    sa.Column('total_shadow_area_m2', sa.Float(), nullable=True),
    sa.Column('plot_area_m2', sa.Float(), nullable=True),
    sa.Column('heatmap_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sample_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_simulations_params_hash'), 'solar_simulations', ['params_hash'], unique=False)
    op.create_index(op.f('ix_solar_simulations_plot_id'), 'solar_simulations', ['plot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solar_simulations_plot_id'), table_name='solar_simulations')
    op.drop_index(op.f('ix_solar_simulations_params_hash'), table_name='solar_simulations')
    op.drop_table('solar_simulations')
    # ### end Alembic commands ###
